use crate::validators;

/// Структурний валідатор: розбирає внутрішню структуру формату, щоб отримати
/// точну межу файлу. Повертає `(offset_end, confidence)` або `None`,
/// якщо структуру розібрати не вдалося (тоді застосовується `end_marker`
/// або евристика).
pub type Validator = fn(&[u8], usize) -> Option<(usize, u8)>;

/// Витягує ім'я файлу/запису, вбудоване у структуру формату (напр. запис
/// каталогу TAR/CPIO/ar/WAD/PAK), якщо воно є. `None`, якщо формат не
/// зберігає імен (більшість "одиночних" форматів) або структуру не вдалося
/// розібрати.
pub type NameExtractor = fn(&[u8], usize) -> Option<String>;

/// Опис однієї сигнатури формату файлу.
pub struct Signature {
    /// Назва формату (напр. "PNG", "ZIP").
    pub name: &'static str,
    /// Людський опис для виводу.
    pub description: &'static str,
    /// Байти магічного числа.
    pub magic: &'static [u8],
    /// Зсув магічних байтів відносно початку самого файлу
    /// (0 для більшості форматів, >0 для форматів на кшталт TAR,
    /// де магічні байти лежать усередині заголовка).
    pub relative_offset: usize,
    /// Структурний валідатор точних меж — має пріоритет над `end_marker`.
    pub validator: Option<Validator>,
    /// Маркер кінця файлу, якщо формат його має (шукається після magic).
    /// Використовується, лише якщо `validator` відсутній або не спрацював.
    pub end_marker: Option<&'static [u8]>,
    /// Розширення файлу для іменування витягнутих фрагментів.
    pub extension: &'static str,
    /// Витягує вбудоване ім'я файлу/запису, якщо формат його зберігає
    /// (TAR/CPIO/ar/WAD/PAK тощо). `None` для форматів без такої концепції.
    pub name_extractor: Option<NameExtractor>,
}

/// Розширення файлу за назвою формату — для іменування витягнутих фрагментів.
pub fn extension_for(format_name: &str) -> &'static str {
    SIGNATURES
        .iter()
        .find(|s| s.name == format_name)
        .map(|s| s.extension)
        .unwrap_or("bin")
}

/// Вбудована база сигнатур найпоширеніших форматів.
/// Джерело: сигнатури, портовані з бази `file(1)`/`libmagic` (BSD license).
pub const SIGNATURES: &[Signature] = &[
    Signature {
        name: "PNG",
        description: "PNG image",
        magic: b"\x89PNG\r\n\x1a\n",
        relative_offset: 0,
        validator: Some(validators::validate_png),
        end_marker: Some(b"IEND\xae\x42\x60\x82"), // "IEND" + CRC32("IEND"), фолбек якщо валідатор не спрацював
        extension: "png",
        name_extractor: None,
    },
    Signature {
        name: "JPEG",
        description: "JPEG image",
        magic: b"\xff\xd8\xff",
        relative_offset: 0,
        validator: Some(validators::validate_jpeg),
        end_marker: Some(b"\xff\xd9"),
        extension: "jpg",
        name_extractor: None,
    },
    Signature {
        name: "GIF87a",
        description: "GIF image (87a)",
        magic: b"GIF87a",
        relative_offset: 0,
        validator: None,
        end_marker: Some(b"\x00\x3b"),
        extension: "gif",
        name_extractor: None,
    },
    Signature {
        name: "GIF89a",
        description: "GIF image (89a)",
        magic: b"GIF89a",
        relative_offset: 0,
        validator: None,
        end_marker: Some(b"\x00\x3b"),
        extension: "gif",
        name_extractor: None,
    },
    Signature {
        name: "ZIP",
        description: "ZIP archive",
        magic: b"PK\x03\x04",
        relative_offset: 0,
        validator: Some(validators::validate_zip),
        end_marker: None,
        extension: "zip",
        name_extractor: None,
    },
    Signature {
        name: "GZIP",
        description: "GZIP compressed data",
        magic: b"\x1f\x8b\x08",
        relative_offset: 0,
        validator: Some(validators::validate_gzip),
        end_marker: None,
        extension: "gz",
        name_extractor: None,
    },
    Signature {
        name: "BZIP2",
        description: "BZIP2 compressed data",
        magic: b"BZh",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "bz2",
        name_extractor: None,
    },
    Signature {
        name: "PDF",
        description: "PDF document",
        magic: b"%PDF-",
        relative_offset: 0,
        validator: None,
        end_marker: Some(b"%%EOF"),
        extension: "pdf",
        name_extractor: None,
    },
    Signature {
        name: "ELF",
        description: "ELF executable",
        magic: b"\x7fELF",
        relative_offset: 0,
        validator: Some(validators::validate_elf),
        end_marker: None,
        extension: "elf",
        name_extractor: None,
    },
    Signature {
        name: "PE",
        description: "PE/DOS executable (MZ header)",
        magic: b"MZ",
        relative_offset: 0,
        validator: Some(validators::validate_pe),
        end_marker: None,
        extension: "exe",
        name_extractor: None,
    },
    Signature {
        name: "BMP",
        description: "BMP image",
        magic: b"BM",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "bmp",
        name_extractor: None,
    },
    Signature {
        name: "TAR",
        description: "TAR archive (ustar)",
        magic: b"ustar",
        relative_offset: 257,
        validator: Some(validators::validate_tar),
        end_marker: None,
        extension: "tar",
        name_extractor: Some(validators::extract_tar_name),
    },
    Signature {
        name: "SQLite",
        description: "SQLite database",
        magic: b"SQLite format 3\0",
        relative_offset: 0,
        validator: Some(validators::validate_sqlite),
        end_marker: None,
        extension: "sqlite",
        name_extractor: None,
    },
    Signature {
        name: "RAR",
        description: "RAR archive",
        magic: b"Rar!\x1a\x07\x00",
        relative_offset: 0,
        validator: Some(validators::validate_rar),
        end_marker: None,
        extension: "rar",
        name_extractor: None,
    },
    Signature {
        name: "7Z",
        description: "7-Zip archive",
        magic: b"7z\xbc\xaf\x27\x1c",
        relative_offset: 0,
        validator: Some(validators::validate_7z),
        end_marker: None,
        extension: "7z",
        name_extractor: None,
    },
    Signature {
        name: "TIFF-LE",
        description: "TIFF image (little-endian)",
        magic: b"II*\x00",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "tiff",
        name_extractor: None,
    },
    Signature {
        name: "TIFF-BE",
        description: "TIFF image (big-endian)",
        magic: b"MM\x00*",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "tiff",
        name_extractor: None,
    },
    Signature {
        name: "ICO",
        description: "Windows icon",
        magic: b"\x00\x00\x01\x00",
        relative_offset: 0,
        validator: Some(validators::validate_ico),
        end_marker: None,
        extension: "ico",
        name_extractor: None,
    },
    Signature {
        name: "CUR",
        description: "Windows cursor",
        magic: b"\x00\x00\x02\x00",
        relative_offset: 0,
        validator: Some(validators::validate_ico),
        end_marker: None,
        extension: "cur",
        name_extractor: None,
    },
    Signature {
        name: "ICNS",
        description: "Apple icon image",
        magic: b"icns",
        relative_offset: 0,
        validator: Some(validators::validate_icns),
        end_marker: None,
        extension: "icns",
        name_extractor: None,
    },
    Signature {
        name: "WEBP",
        description: "WebP image",
        magic: b"WEBP",
        relative_offset: 8, // "RIFF" + size(4) + "WEBP" — form-тип лежить за офсетом 8
        validator: Some(validators::validate_riff),
        end_marker: None,
        extension: "webp",
        name_extractor: None,
    },
    Signature {
        name: "CDR",
        description: "CorelDRAW image (RIFF-based)",
        magic: b"CDR",
        relative_offset: 8, // "RIFF" + size(4) + "CDR" + версія (CDR2..CDR9, CDRX тощо)
        validator: Some(validators::validate_riff),
        end_marker: None,
        extension: "cdr",
        name_extractor: None,
    },
    Signature {
        name: "PSD",
        description: "Adobe Photoshop image",
        magic: b"8BPS",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "psd",
        name_extractor: None,
    },
    Signature {
        name: "HEIC",
        description: "HEIC image (ISOBMFF, brand 'heic')",
        magic: b"heic",
        relative_offset: 8, // бокс "ftyp": size(4)+type(4)="ftyp"+major_brand(4)
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "heic",
        name_extractor: None,
    },
    Signature {
        name: "HEIC-10bit",
        description: "HEIC image, 10-bit (ISOBMFF, brand 'heix')",
        magic: b"heix",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "heic",
        name_extractor: None,
    },
    Signature {
        name: "AVIF",
        description: "AVIF image (ISOBMFF, brand 'avif')",
        magic: b"avif",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "avif",
        name_extractor: None,
    },
    Signature {
        name: "AVIF-sequence",
        description: "AVIF image sequence (ISOBMFF, brand 'avis')",
        magic: b"avis",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "avif",
        name_extractor: None,
    },
    Signature {
        name: "JP2",
        description: "JPEG 2000 image",
        magic: b"jP  ",
        relative_offset: 4, // бокс-сигнатура: size(4)+type(4)="jP  "
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "jp2",
        name_extractor: None,
    },
    Signature {
        name: "JXL",
        description: "JPEG XL image (boxed container)",
        magic: b"JXL ",
        relative_offset: 4,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "jxl",
        name_extractor: None,
    },
    Signature {
        name: "XCF",
        description: "GIMP native image",
        magic: b"gimp xcf",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "xcf",
        name_extractor: None,
    },
    Signature {
        name: "PSP",
        description: "Paint Shop Pro image",
        magic: b"Paint Shop Pro Image File",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "psp",
        name_extractor: None,
    },
    Signature {
        name: "XPM",
        description: "X PixMap image",
        magic: b"/* XPM */",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "xpm",
        name_extractor: None,
    },
    Signature {
        name: "DDS",
        description: "DirectDraw Surface texture",
        magic: b"DDS ",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "dds",
        name_extractor: None,
    },
    Signature {
        name: "EXR",
        description: "OpenEXR HDR image",
        magic: b"\x76\x2f\x31\x01",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "exr",
        name_extractor: None,
    },
    Signature {
        name: "JBIG2",
        description: "JBIG2 image (file format)",
        magic: b"\x97JB2\r\n\x1a\n",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "jb2",
        name_extractor: None,
    },
    Signature {
        name: "PPM",
        description: "Netpbm portable pixmap (binary)",
        magic: b"P6",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "ppm",
        name_extractor: None,
    },
    Signature {
        name: "PGM",
        description: "Netpbm portable graymap (binary)",
        magic: b"P5",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "pgm",
        name_extractor: None,
    },
    Signature {
        name: "PBM",
        description: "Netpbm portable bitmap (binary)",
        magic: b"P4",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "pbm",
        name_extractor: None,
    },
    Signature {
        name: "FLIF",
        description: "Free Lossless Image Format",
        magic: b"FLIF",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "flif",
        name_extractor: None,
    },
    Signature {
        name: "SVG",
        description: "SVG vector image (XML)",
        magic: b"<svg",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "svg",
        name_extractor: None,
    },
    Signature {
        name: "EPS",
        description: "Encapsulated PostScript / legacy Adobe Illustrator",
        magic: b"%!PS-Adobe",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "eps",
        name_extractor: None,
    },
    Signature {
        name: "EPS-Binary",
        description: "EPS with DOS binary header (embedded PS/WMF/TIFF preview)",
        magic: b"\xc5\xd0\xd3\xc6",
        relative_offset: 0,
        validator: Some(validators::validate_eps_binary_header),
        end_marker: None,
        extension: "eps",
        name_extractor: None,
    },
    Signature {
        name: "WMF-Placeable",
        description: "Windows Metafile (placeable)",
        magic: b"\xd7\xcd\xc6\x9a\x00\x00",
        relative_offset: 0,
        validator: Some(validators::validate_wmf),
        end_marker: None,
        extension: "wmf",
        name_extractor: None,
    },
    Signature {
        name: "WMF",
        description: "Windows Metafile (standard, without placeable wrapper)",
        magic: b"\x01\x00\x09\x00",
        relative_offset: 0,
        validator: Some(validators::validate_wmf),
        end_marker: None,
        extension: "wmf",
        name_extractor: None,
    },
    Signature {
        name: "EMF",
        description: "Enhanced Metafile",
        magic: b" EMF",
        relative_offset: 40, // dSignature лежить за офсетом 40 у заголовку ENHMETAHEADER
        validator: Some(validators::validate_emf),
        end_marker: None,
        extension: "emf",
        name_extractor: None,
    },
    Signature {
        name: "MNG",
        description: "Multiple-image Network Graphics",
        magic: b"\x8aMNG\r\n\x1a\n",
        relative_offset: 0,
        validator: Some(validators::validate_mng),
        end_marker: None,
        extension: "mng",
        name_extractor: None,
    },
    Signature {
        name: "JNG",
        description: "JPEG Network Graphics",
        magic: b"\x8bJNG\r\n\x1a\n",
        relative_offset: 0,
        validator: Some(validators::validate_jng),
        end_marker: None,
        extension: "jng",
        name_extractor: None,
    },
    Signature {
        name: "PICT",
        description: "Classic Mac QuickDraw PICT (v2)",
        magic: b"\x00\x11\x02\xff",
        relative_offset: 522, // 512-байтовий (часто ігнорований) заголовок + 10-байтовий PICT-заголовок
        validator: None,
        end_marker: None,
        extension: "pict",
        name_extractor: None,
    },
    Signature {
        name: "XFig",
        description: "Xfig vector drawing",
        magic: b"#FIG",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "fig",
        name_extractor: None,
    },
    Signature {
        name: "Mach-O-32-BE",
        description: "Mach-O executable, 32-bit big-endian (macOS/NeXTSTEP PowerPC/68k)",
        magic: b"\xfe\xed\xfa\xce",
        relative_offset: 0,
        validator: Some(validators::validate_macho_32be),
        end_marker: None,
        extension: "macho",
        name_extractor: None,
    },
    Signature {
        name: "Mach-O-32-LE",
        description: "Mach-O executable, 32-bit little-endian (macOS i386)",
        magic: b"\xce\xfa\xed\xfe",
        relative_offset: 0,
        validator: Some(validators::validate_macho_32le),
        end_marker: None,
        extension: "macho",
        name_extractor: None,
    },
    Signature {
        name: "Mach-O-64-BE",
        description: "Mach-O executable, 64-bit big-endian (macOS/NeXTSTEP PowerPC64)",
        magic: b"\xfe\xed\xfa\xcf",
        relative_offset: 0,
        validator: Some(validators::validate_macho_64be),
        end_marker: None,
        extension: "macho",
        name_extractor: None,
    },
    Signature {
        name: "Mach-O-64-LE",
        description: "Mach-O executable, 64-bit little-endian (macOS x86_64/arm64)",
        magic: b"\xcf\xfa\xed\xfe",
        relative_offset: 0,
        validator: Some(validators::validate_macho_64le),
        end_marker: None,
        extension: "macho",
        name_extractor: None,
    },
    Signature {
        name: "Mach-O-Fat",
        description: "Mach-O Universal/Fat Binary (multi-architecture macOS executable)",
        magic: b"\xca\xfe\xba\xbe",
        relative_offset: 0,
        validator: Some(validators::validate_macho_fat),
        end_marker: None,
        extension: "macho",
        name_extractor: None,
    },
    Signature {
        name: "PEF",
        description: "Preferred Executable Format (classic Mac OS PowerPC / BeOS PPC)",
        magic: b"Joy!peff",
        relative_offset: 0,
        validator: Some(validators::validate_pef),
        end_marker: None,
        extension: "pef",
        name_extractor: None,
    },
    Signature {
        name: "Amiga-Hunk",
        description: "AmigaOS Hunk executable",
        magic: b"\x00\x00\x03\xf3",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "amiga",
        name_extractor: None,
    },
    Signature {
        name: "XCOFF32",
        description: "XCOFF executable, 32-bit (AIX PowerPC)",
        magic: b"\x01\xdf",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "xcoff",
        name_extractor: None,
    },
    Signature {
        name: "XCOFF64",
        description: "XCOFF executable, 64-bit (AIX PowerPC)",
        magic: b"\x01\xf7",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "xcoff",
        name_extractor: None,
    },
    Signature {
        name: "Atari-ST",
        description: "Atari ST GEMDOS executable",
        magic: b"\x60\x1a",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "prg",
        name_extractor: None,
    },
    Signature {
        name: "MP3",
        description: "MP3 audio (ID3v2 tag)",
        magic: b"ID3",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "mp3",
        name_extractor: None,
    },
    Signature {
        name: "M4A",
        description: "M4A/AAC audio (ISOBMFF, brand 'M4A ')",
        magic: b"M4A ",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "m4a",
        name_extractor: None,
    },
    Signature {
        name: "OGG",
        description: "Ogg container (Vorbis/Opus/Speex/Ogg-FLAC)",
        magic: b"OggS",
        relative_offset: 0,
        validator: Some(validators::validate_ogg),
        end_marker: None,
        extension: "ogg",
        name_extractor: None,
    },
    Signature {
        name: "ASF",
        description: "ASF container (Windows Media Audio/WMA або Windows Media Video/WMV)",
        magic: b"\x30\x26\xb2\x75\x8e\x66\xcf\x11\xa6\xd9\x00\xaa\x00\x62\xce\x6c",
        relative_offset: 0,
        validator: Some(validators::validate_asf),
        end_marker: None,
        extension: "wma",
        name_extractor: None,
    },
    Signature {
        name: "WAV",
        description: "WAV audio (RIFF-based, PCM/lossless)",
        magic: b"WAVE",
        relative_offset: 8,
        validator: Some(validators::validate_riff),
        end_marker: None,
        extension: "wav",
        name_extractor: None,
    },
    Signature {
        name: "AIFF",
        description: "AIFF audio (IFF-based, PCM/lossless)",
        magic: b"AIFF",
        relative_offset: 8,
        validator: Some(validators::validate_iff),
        end_marker: None,
        extension: "aiff",
        name_extractor: None,
    },
    Signature {
        name: "AIFC",
        description: "AIFF-C audio (IFF-based, compressed)",
        magic: b"AIFC",
        relative_offset: 8,
        validator: Some(validators::validate_iff),
        end_marker: None,
        extension: "aifc",
        name_extractor: None,
    },
    Signature {
        name: "8SVX",
        description: "Amiga 8SVX audio (IFF-based, 8-bit sampled voice)",
        magic: b"8SVX",
        relative_offset: 8,
        validator: Some(validators::validate_iff),
        end_marker: None,
        extension: "8svx",
        name_extractor: None,
    },
    Signature {
        name: "FLAC",
        description: "FLAC audio (lossless compressed)",
        magic: b"fLaC",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "flac",
        name_extractor: None,
    },
    Signature {
        name: "APE",
        description: "Monkey's Audio (lossless compressed)",
        magic: b"MAC ",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "ape",
        name_extractor: None,
    },
    Signature {
        name: "WavPack",
        description: "WavPack audio (lossless compressed)",
        magic: b"wvpk",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "wv",
        name_extractor: None,
    },
    Signature {
        name: "TTA",
        description: "True Audio (lossless compressed)",
        magic: b"TTA1",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "tta",
        name_extractor: None,
    },
    Signature {
        name: "DSF",
        description: "Sony DSD Stream File (high-res lossless)",
        magic: b"DSD ",
        relative_offset: 0,
        validator: Some(validators::validate_dsf),
        end_marker: None,
        extension: "dsf",
        name_extractor: None,
    },
    Signature {
        name: "CAF",
        description: "Apple Core Audio Format",
        magic: b"caff",
        relative_offset: 0,
        validator: Some(validators::validate_caf),
        end_marker: None,
        extension: "caf",
        name_extractor: None,
    },
    Signature {
        name: "MIDI",
        description: "Standard MIDI File",
        magic: b"MThd",
        relative_offset: 0,
        validator: Some(validators::validate_midi),
        end_marker: None,
        extension: "mid",
        name_extractor: None,
    },
    Signature {
        name: "MOD-MK",
        description: "ProTracker module (M.K., 4 channels)",
        magic: b"M.K.",
        relative_offset: 1080,
        validator: Some(validators::validate_mod),
        end_marker: None,
        extension: "mod",
        name_extractor: None,
    },
    Signature {
        name: "MOD-FLT4",
        description: "FastTracker module (FLT4, 4 channels)",
        magic: b"FLT4",
        relative_offset: 1080,
        validator: Some(validators::validate_mod),
        end_marker: None,
        extension: "mod",
        name_extractor: None,
    },
    Signature {
        name: "MOD-6CHN",
        description: "ProTracker module (6CHN, 6 channels)",
        magic: b"6CHN",
        relative_offset: 1080,
        validator: None,
        end_marker: None,
        extension: "mod",
        name_extractor: None,
    },
    Signature {
        name: "MOD-8CHN",
        description: "ProTracker module (8CHN, 8 channels)",
        magic: b"8CHN",
        relative_offset: 1080,
        validator: None,
        end_marker: None,
        extension: "mod",
        name_extractor: None,
    },
    Signature {
        name: "XM",
        description: "FastTracker 2 Extended Module",
        magic: b"Extended Module: ",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "xm",
        name_extractor: None,
    },
    Signature {
        name: "S3M",
        description: "ScreamTracker 3 module",
        magic: b"SCRM",
        relative_offset: 44,
        validator: None,
        end_marker: None,
        extension: "s3m",
        name_extractor: None,
    },
    Signature {
        name: "IT",
        description: "Impulse Tracker module",
        magic: b"IMPM",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "it",
        name_extractor: None,
    },
    Signature {
        name: "CPIO-newc",
        description: "CPIO archive (\"newc\" ASCII format, e.g. initramfs)",
        magic: b"070701",
        relative_offset: 0,
        validator: Some(validators::validate_cpio_newc),
        end_marker: None,
        extension: "cpio",
        name_extractor: Some(validators::extract_cpio_newc_name),
    },
    Signature {
        name: "CPIO-crc",
        description: "CPIO archive (\"crc\" ASCII format)",
        magic: b"070702",
        relative_offset: 0,
        validator: Some(validators::validate_cpio_newc),
        end_marker: None,
        extension: "cpio",
        name_extractor: Some(validators::extract_cpio_newc_name),
    },
    Signature {
        name: "CPIO-odc",
        description: "CPIO archive (\"odc\" old ASCII/portable format)",
        magic: b"070707",
        relative_offset: 0,
        validator: Some(validators::validate_cpio_odc),
        end_marker: None,
        extension: "cpio",
        name_extractor: Some(validators::extract_cpio_odc_name),
    },
    Signature {
        name: "AR",
        description: "Unix ar archive (static libraries .a, Debian .deb)",
        magic: b"!<arch>\n",
        relative_offset: 0,
        validator: Some(validators::validate_ar),
        end_marker: None,
        extension: "a",
        name_extractor: Some(validators::extract_ar_name),
    },
    Signature {
        name: "XAR",
        description: "eXtensible ARchive (macOS .pkg installers)",
        magic: b"xar!",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "xar",
        name_extractor: None,
    },
    Signature {
        name: "ISO9660",
        description: "ISO 9660 CD/DVD disc image",
        magic: b"CD001",
        relative_offset: 32769, // сектор 16 (офсет 32768) + офсет 1 самого StdID у Primary Volume Descriptor
        validator: Some(validators::validate_iso9660),
        end_marker: None,
        extension: "iso",
        name_extractor: None,
    },
    Signature {
        name: "ZSTD",
        description: "Zstandard compressed data",
        magic: b"\x28\xb5\x2f\xfd",
        relative_offset: 0,
        validator: Some(validators::validate_zstd),
        end_marker: None,
        extension: "zst",
        name_extractor: None,
    },
    Signature {
        name: "LZ4",
        description: "LZ4 frame format compressed data",
        magic: b"\x04\x22\x4d\x18",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "lz4",
        name_extractor: None,
    },
    Signature {
        name: "XZ",
        description: "XZ compressed data (LZMA2)",
        magic: b"\xfd\x37\x7a\x58\x5a\x00",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "xz",
        name_extractor: None,
    },
    Signature {
        name: "LZO",
        description: "lzop compressed data",
        magic: b"\x89LZO\x00\x0d\x0a\x1a\x0a",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "lzo",
        name_extractor: None,
    },
    Signature {
        name: "WAD-I",
        description: "WAD archive, IWAD (Doom/Doom II/Heretic/Hexen — id Software)",
        magic: b"IWAD",
        relative_offset: 0,
        validator: Some(validators::validate_wad),
        end_marker: None,
        extension: "wad",
        name_extractor: Some(validators::extract_wad_name),
    },
    Signature {
        name: "WAD-P",
        description: "WAD archive, PWAD (Doom mod/patch WAD)",
        magic: b"PWAD",
        relative_offset: 0,
        validator: Some(validators::validate_wad),
        end_marker: None,
        extension: "wad",
        name_extractor: Some(validators::extract_wad_name),
    },
    Signature {
        name: "PAK-Quake",
        description: "Quake PAK archive",
        magic: b"PACK",
        relative_offset: 0,
        validator: Some(validators::validate_pak_quake),
        end_marker: None,
        extension: "pak",
        name_extractor: Some(validators::extract_pak_name),
    },
    Signature {
        name: "VBSP",
        description: "Source engine BSP map (Half-Life 2, CS:S, Portal, TF2, L4D)",
        magic: b"VBSP",
        relative_offset: 0,
        validator: Some(validators::validate_vbsp),
        end_marker: None,
        extension: "bsp",
        name_extractor: None,
    },
    Signature {
        name: "NES",
        description: "NES ROM (iNES format)",
        magic: b"NES\x1a",
        relative_offset: 0,
        validator: Some(validators::validate_nes),
        end_marker: None,
        extension: "nes",
        name_extractor: None,
    },
    Signature {
        name: "Genesis",
        description: "Sega Genesis/Mega Drive ROM",
        magic: b"SEGA",
        relative_offset: 0x100,
        validator: None,
        end_marker: None,
        extension: "bin",
        name_extractor: None,
    },
    Signature {
        name: "UnityFS",
        description: "Unity Engine Asset Bundle",
        magic: b"UnityFS\x00",
        relative_offset: 0,
        validator: Some(validators::validate_unityfs),
        end_marker: None,
        extension: "unity3d",
        name_extractor: None,
    },
    Signature {
        name: "Godot-PCK",
        description: "Godot Engine game data package",
        magic: b"GDPC",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "pck",
        name_extractor: None,
    },
    Signature {
        name: "RPA",
        description: "Ren'Py archive (visual novels)",
        magic: b"RPA-3.0\n",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "rpa",
        name_extractor: None,
    },
    Signature {
        name: "VPK",
        description: "Source engine VPK archive (CS:GO, TF2, Dota 2, HL2, Portal)",
        magic: b"\x34\x12\xaa\x55",
        relative_offset: 0,
        validator: Some(validators::validate_vpk),
        end_marker: None,
        extension: "vpk",
        name_extractor: None,
    },
    Signature {
        name: "SWF-uncompressed",
        description: "Adobe/Macromedia Flash movie, uncompressed (застарілий — знято з підтримки браузерами 2021)",
        magic: b"FWS",
        relative_offset: 0,
        validator: Some(validators::validate_swf),
        end_marker: None,
        extension: "swf",
        name_extractor: None,
    },
    Signature {
        name: "SWF-zlib",
        description: "Adobe/Macromedia Flash movie, zlib-стиснений",
        magic: b"CWS",
        relative_offset: 0,
        validator: Some(validators::validate_swf),
        end_marker: None,
        extension: "swf",
        name_extractor: None,
    },
    Signature {
        name: "SWF-lzma",
        description: "Adobe Flash movie, LZMA-стиснений",
        magic: b"ZWS",
        relative_offset: 0,
        validator: Some(validators::validate_swf),
        end_marker: None,
        extension: "swf",
        name_extractor: None,
    },
    Signature {
        name: "Shockwave-Director",
        description: "Macromedia/Adobe Shockwave Director movie (застарілий, замінений HTML5)",
        magic: b"RIFX",
        relative_offset: 0,
        validator: Some(validators::validate_rifx),
        end_marker: None,
        extension: "dcr",
        name_extractor: None,
    },
    Signature {
        name: "RealMedia",
        description: "RealMedia/RealAudio (застарілий стрімінговий формат RealNetworks)",
        magic: b".RMF",
        relative_offset: 0,
        validator: Some(validators::validate_realmedia),
        end_marker: None,
        extension: "rm",
        name_extractor: None,
    },
    Signature {
        name: "VOC",
        description: "Creative Voice File (Sound Blaster, DOS, застарілий)",
        magic: b"Creative Voice File\x1a",
        relative_offset: 0,
        validator: Some(validators::validate_voc),
        end_marker: None,
        extension: "voc",
        name_extractor: None,
    },
    Signature {
        name: "ILBM",
        description: "Amiga IFF ILBM image (застарілий растровий формат)",
        magic: b"ILBM",
        relative_offset: 8,
        validator: Some(validators::validate_iff),
        end_marker: None,
        extension: "ilbm",
        name_extractor: None,
    },
    Signature {
        name: "OLE2",
        description: "OLE2/Compound File (застарілі MS Office .doc/.xls/.ppt до 2007, Outlook .msg, .msi)",
        magic: b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "doc",
        name_extractor: None,
    },
    Signature {
        name: "CHM",
        description: "Compiled HTML Help (наступник застарілого WinHelp .hlp, сам тепер теж застарілий)",
        magic: b"ITSF",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "chm",
        name_extractor: None,
    },
    Signature {
        name: "MP4-isom",
        description: "MP4 video (ISOBMFF, brand 'isom')",
        magic: b"isom",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "mp4",
        name_extractor: None,
    },
    Signature {
        name: "MP4-mp42",
        description: "MP4 video (ISOBMFF, brand 'mp42')",
        magic: b"mp42",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "mp4",
        name_extractor: None,
    },
    Signature {
        name: "MOV",
        description: "QuickTime video (ISOBMFF, brand 'qt  ')",
        magic: b"qt  ",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "mov",
        name_extractor: None,
    },
    Signature {
        name: "3GP",
        description: "3GP video (ISOBMFF, brand '3gp4')",
        magic: b"3gp4",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "3gp",
        name_extractor: None,
    },
    Signature {
        name: "3G2",
        description: "3GPP2 video (ISOBMFF, brand '3g2a')",
        magic: b"3g2a",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "3g2",
        name_extractor: None,
    },
    Signature {
        name: "M4V",
        description: "iTunes video (ISOBMFF, brand 'M4V ')",
        magic: b"M4V ",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "m4v",
        name_extractor: None,
    },
    Signature {
        name: "AVI",
        description: "AVI video (RIFF-based)",
        magic: b"AVI ",
        relative_offset: 8,
        validator: Some(validators::validate_riff),
        end_marker: None,
        extension: "avi",
        name_extractor: None,
    },
    Signature {
        name: "EBML",
        description: "EBML/Matroska container (охоплює і .mkv, і .webm — той самий формат)",
        magic: b"\x1a\x45\xdf\xa3",
        relative_offset: 0,
        validator: Some(validators::validate_ebml),
        end_marker: None,
        extension: "mkv",
        name_extractor: None,
    },
    Signature {
        name: "FLV",
        description: "Flash Video",
        magic: b"FLV",
        relative_offset: 0,
        validator: Some(validators::validate_flv),
        end_marker: None,
        extension: "flv",
        name_extractor: None,
    },
    Signature {
        name: "MPEG-PS",
        description: "MPEG Program Stream (класичні .mpg/.mpeg, а також DVD Video Object .vob — той самий pack_start_code)",
        magic: b"\x00\x00\x01\xba",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "mpg",
        name_extractor: None,
    },
    Signature {
        name: "MPEG-ES",
        description: "MPEG-1/2 video elementary stream (сирий, без Program Stream обгортки)",
        magic: b"\x00\x00\x01\xb3",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "m2v",
        name_extractor: None,
    },
    // --- ISOBMFF: додаткові бренди, перевикористовують готовий validate_isobmff ---
    Signature {
        name: "MP4-mp41",
        description: "MP4 video (ISOBMFF, brand 'mp41')",
        magic: b"mp41",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "mp4",
        name_extractor: None,
    },
    Signature {
        name: "MP4-avc1",
        description: "MP4 video, H.264 (ISOBMFF, brand 'avc1')",
        magic: b"avc1",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "mp4",
        name_extractor: None,
    },
    Signature {
        name: "MP4-iso2",
        description: "MP4 video (ISOBMFF, brand 'iso2')",
        magic: b"iso2",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "mp4",
        name_extractor: None,
    },
    Signature {
        name: "M4B",
        description: "iTunes audiobook (ISOBMFF, brand 'M4B ')",
        magic: b"M4B ",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "m4b",
        name_extractor: None,
    },
    Signature {
        name: "M4P",
        description: "iTunes protected audio (ISOBMFF, brand 'M4P ')",
        magic: b"M4P ",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "m4p",
        name_extractor: None,
    },
    Signature {
        name: "HEIF-mif1",
        description: "HEIF still image, generic (ISOBMFF, brand 'mif1')",
        magic: b"mif1",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "heif",
        name_extractor: None,
    },
    Signature {
        name: "HEIF-msf1",
        description: "HEIF multi-image (ISOBMFF, brand 'msf1')",
        magic: b"msf1",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "heif",
        name_extractor: None,
    },
    Signature {
        name: "3GP-3gp5",
        description: "3GPP Release 5 video (ISOBMFF, brand '3gp5')",
        magic: b"3gp5",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "3gp",
        name_extractor: None,
    },
    Signature {
        name: "HEIF-heis",
        description: "HEIF image sequence (ISOBMFF, brand 'heis')",
        magic: b"heis",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "heic",
        name_extractor: None,
    },
    Signature {
        name: "HEIF-hevc",
        description: "HEVC-coded HEIF image (ISOBMFF, brand 'hevc')",
        magic: b"hevc",
        relative_offset: 8,
        validator: Some(validators::validate_isobmff),
        end_marker: None,
        extension: "heic",
        name_extractor: None,
    },
    // --- RIFF: додаткові form-типи, перевикористовують готовий validate_riff ---
    Signature {
        name: "ANI",
        description: "Windows animated cursor (RIFF-based)",
        magic: b"ACON",
        relative_offset: 8,
        validator: Some(validators::validate_riff),
        end_marker: None,
        extension: "ani",
        name_extractor: None,
    },
    Signature {
        name: "RMID",
        description: "MIDI wrapped in RIFF",
        magic: b"RMID",
        relative_offset: 8,
        validator: Some(validators::validate_riff),
        end_marker: None,
        extension: "rmi",
        name_extractor: None,
    },
    Signature {
        name: "RIFF-PAL",
        description: "RIFF palette file",
        magic: b"PAL ",
        relative_offset: 8,
        validator: Some(validators::validate_riff),
        end_marker: None,
        extension: "pal",
        name_extractor: None,
    },
    Signature {
        name: "RDIB",
        description: "Device-independent bitmap wrapped in RIFF",
        magic: b"RDIB",
        relative_offset: 8,
        validator: Some(validators::validate_riff),
        end_marker: None,
        extension: "rdi",
        name_extractor: None,
    },
    // --- IFF: додаткові form-типи, перевикористовують готовий validate_iff ---
    Signature {
        name: "ANIM",
        description: "Amiga IFF animation",
        magic: b"ANIM",
        relative_offset: 8,
        validator: Some(validators::validate_iff),
        end_marker: None,
        extension: "anim",
        name_extractor: None,
    },
    Signature {
        name: "ANBM",
        description: "Amiga IFF animated bitmap",
        magic: b"ANBM",
        relative_offset: 8,
        validator: Some(validators::validate_iff),
        end_marker: None,
        extension: "anbm",
        name_extractor: None,
    },
    // --- Нові валідатори з прямим полем розміру або прохідною структурою ---
    Signature {
        name: "WOFF",
        description: "Web Open Font Format",
        magic: b"wOFF",
        relative_offset: 0,
        validator: Some(validators::validate_woff),
        end_marker: None,
        extension: "woff",
        name_extractor: None,
    },
    Signature {
        name: "WOFF2",
        description: "Web Open Font Format 2",
        magic: b"wOF2",
        relative_offset: 0,
        validator: Some(validators::validate_woff),
        end_marker: None,
        extension: "woff2",
        name_extractor: None,
    },
    Signature {
        name: "glTF-Binary",
        description: "glTF Binary 3D model (.glb)",
        magic: b"glTF",
        relative_offset: 0,
        validator: Some(validators::validate_glb),
        end_marker: None,
        extension: "glb",
        name_extractor: None,
    },
    Signature {
        name: "MPQ",
        description: "MPQ archive (Blizzard — Warcraft III, StarCraft, Diablo, World of Warcraft)",
        magic: b"MPQ\x1a",
        relative_offset: 0,
        validator: Some(validators::validate_mpq),
        end_marker: None,
        extension: "mpq",
        name_extractor: None,
    },
    Signature {
        name: "SquashFS",
        description: "SquashFS filesystem image (Snap-пакунки, вбудовані Linux-системи)",
        magic: b"hsqs",
        relative_offset: 0,
        validator: Some(validators::validate_squashfs),
        end_marker: None,
        extension: "squashfs",
        name_extractor: None,
    },
    Signature {
        name: "CAB",
        description: "Microsoft Cabinet archive",
        magic: b"MSCF",
        relative_offset: 0,
        validator: Some(validators::validate_cab),
        end_marker: None,
        extension: "cab",
        name_extractor: None,
    },
    Signature {
        name: "DEX",
        description: "Android Dalvik executable (classes.dex усередині APK)",
        magic: b"dex\n035\x00",
        relative_offset: 0,
        validator: Some(validators::validate_dex),
        end_marker: None,
        extension: "dex",
        name_extractor: None,
    },
    Signature {
        name: "DPX-BE",
        description: "Digital Picture Exchange (кіноіндустрія), big-endian",
        magic: b"SDPX",
        relative_offset: 0,
        validator: Some(validators::validate_dpx_be),
        end_marker: None,
        extension: "dpx",
        name_extractor: None,
    },
    Signature {
        name: "DPX-LE",
        description: "Digital Picture Exchange (кіноіндустрія), little-endian",
        magic: b"XPDS",
        relative_offset: 0,
        validator: Some(validators::validate_dpx_le),
        end_marker: None,
        extension: "dpx",
        name_extractor: None,
    },
    Signature {
        name: "ICC",
        description: "ICC color profile",
        magic: b"acsp",
        relative_offset: 36,
        validator: Some(validators::validate_icc),
        end_marker: None,
        extension: "icc",
        name_extractor: None,
    },
    Signature {
        name: "AppleSingle",
        description: "AppleSingle (кодування ресурсної гілки класичного Mac OS)",
        magic: b"\x00\x05\x16\x00\x00\x02\x00\x00",
        relative_offset: 0,
        validator: Some(validators::validate_apple_single_double),
        end_marker: None,
        extension: "as",
        name_extractor: None,
    },
    Signature {
        name: "AppleDouble",
        description: "AppleDouble (саме так macOS зберігає метадані у файлах '._ім'я' на не-HFS+ файлових системах)",
        magic: b"\x00\x05\x16\x07\x00\x02\x00\x00",
        relative_offset: 0,
        validator: Some(validators::validate_apple_single_double),
        end_marker: None,
        extension: "adf",
        name_extractor: None,
    },
    Signature {
        name: "Blender",
        description: "Blender 3D scene (.blend)",
        magic: b"BLENDER",
        relative_offset: 0,
        validator: Some(validators::validate_blend),
        end_marker: None,
        extension: "blend",
        name_extractor: None,
    },
    Signature {
        name: "AU",
        description: "Sun/NeXT audio",
        magic: b".snd",
        relative_offset: 0,
        validator: Some(validators::validate_au),
        end_marker: None,
        extension: "au",
        name_extractor: None,
    },
    // --- Сигнатурні записи без структурного валідатора ---
    Signature {
        name: "TTF",
        description: "TrueType font",
        magic: b"\x00\x01\x00\x00",
        relative_offset: 0,
        validator: Some(validators::validate_sfnt),
        end_marker: None,
        extension: "ttf",
        name_extractor: None,
    },
    Signature {
        name: "OTF",
        description: "OpenType font (CFF)",
        magic: b"OTTO",
        relative_offset: 0,
        validator: Some(validators::validate_sfnt),
        end_marker: None,
        extension: "otf",
        name_extractor: None,
    },
    Signature {
        name: "TTC",
        description: "TrueType Collection",
        magic: b"ttcf",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "ttc",
        name_extractor: None,
    },
    Signature {
        name: "BDF",
        description: "Bitmap font (X11)",
        magic: b"STARTFONT",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "bdf",
        name_extractor: None,
    },
    Signature {
        name: "QOI",
        description: "Quite OK Image format",
        magic: b"qoif",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "qoi",
        name_extractor: None,
    },
    Signature {
        name: "KTX",
        description: "Khronos Texture format",
        magic: b"\xabKTX 11\xbb\r\n\x1a\n",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "ktx",
        name_extractor: None,
    },
    Signature {
        name: "KTX2",
        description: "Khronos Texture format 2",
        magic: b"\xabKTX 20\xbb\r\n\x1a\n",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "ktx2",
        name_extractor: None,
    },
    Signature {
        name: "HDR",
        description: "Radiance HDR image",
        magic: b"#?RADIANCE\n",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "hdr",
        name_extractor: None,
    },
    Signature {
        name: "PVR",
        description: "PowerVR texture (v3)",
        magic: b"PVR\x03",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "pvr",
        name_extractor: None,
    },
    Signature {
        name: "FBX",
        description: "Autodesk FBX 3D model (binary)",
        magic: b"Kaydara FBX Binary  \x00",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "fbx",
        name_extractor: None,
    },
    Signature {
        name: "PLY",
        description: "Stanford Polygon 3D model",
        magic: b"ply\n",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "ply",
        name_extractor: None,
    },
    Signature {
        name: "VMDK",
        description: "VMware Virtual Disk (sparse)",
        magic: b"KDMV",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "vmdk",
        name_extractor: None,
    },
    Signature {
        name: "VHDX",
        description: "Microsoft Hyper-V Virtual Hard Disk",
        magic: b"vhdxfile",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "vhdx",
        name_extractor: None,
    },
    Signature {
        name: "QCOW2",
        description: "QEMU Copy-On-Write disk image",
        magic: b"QFI\xfb",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "qcow2",
        name_extractor: None,
    },
    Signature {
        name: "VDI",
        description: "VirtualBox Virtual Disk Image",
        magic: b"<<< Oracle VM VirtualBox Disk Image >>>",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "vdi",
        name_extractor: None,
    },
    Signature {
        name: "RPM",
        description: "RPM package (RedHat/Fedora/openSUSE)",
        magic: b"\xed\xab\xee\xdb",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "rpm",
        name_extractor: None,
    },
    Signature {
        name: "Java-Class",
        description: "Java class file (той самий CAFEBABE, що й Mach-O Fat/Universal Binary — реальна двозначність формату)",
        magic: b"\xca\xfe\xba\xbe",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "class",
        name_extractor: None,
    },
    Signature {
        name: "LNK",
        description: "Windows Shell Link (ярлик)",
        magic: b"\x4c\x00\x00\x00\x01\x14\x02\x00\x00\x00\x00\x00\xc0\x00\x00\x00\x00\x00\x00\x46",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "lnk",
        name_extractor: None,
    },
    Signature {
        name: "REG4",
        description: "Windows Registry export (REGEDIT4, текстовий)",
        magic: b"REGEDIT4",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "reg",
        name_extractor: None,
    },
    Signature {
        name: "REG5",
        description: "Windows Registry export (версія 5.00, текстовий)",
        magic: b"Windows Registry Editor Version 5.00",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "reg",
        name_extractor: None,
    },
    Signature {
        name: "BPLIST",
        description: "Apple binary property list",
        magic: b"bplist00",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "plist",
        name_extractor: None,
    },
    Signature {
        name: "HDF5",
        description: "Hierarchical Data Format 5 (наукові/ML дані)",
        magic: b"\x89HDF\r\n\x1a\n",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "h5",
        name_extractor: None,
    },
    Signature {
        name: "NetCDF",
        description: "NetCDF classic format",
        magic: b"CDF\x01",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "nc",
        name_extractor: None,
    },
    Signature {
        name: "MAT",
        description: "MATLAB MAT-file (v5)",
        magic: b"MATLAB 5.0 MAT-file",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "mat",
        name_extractor: None,
    },
    Signature {
        name: "NPY",
        description: "NumPy array file",
        magic: b"\x93NUMPY",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "npy",
        name_extractor: None,
    },
    Signature {
        name: "Parquet",
        description: "Apache Parquet columnar data",
        magic: b"PAR1",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "parquet",
        name_extractor: None,
    },
    Signature {
        name: "Avro",
        description: "Apache Avro container",
        magic: b"Obj\x01",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "avro",
        name_extractor: None,
    },
    Signature {
        name: "ORC",
        description: "Apache ORC columnar data",
        magic: b"ORC",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "orc",
        name_extractor: None,
    },
    Signature {
        name: "WebVTT",
        description: "WebVTT subtitle track",
        magic: b"WEBVTT",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "vtt",
        name_extractor: None,
    },
    Signature {
        name: "ASS",
        description: "Advanced SubStation Alpha subtitle",
        magic: b"[Script Info]",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "ass",
        name_extractor: None,
    },
    Signature {
        name: "PGP-Message",
        description: "OpenPGP ASCII-armored message",
        magic: b"-----BEGIN PGP MESSAGE-----",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "pgp",
        name_extractor: None,
    },
    Signature {
        name: "PGP-PublicKey",
        description: "OpenPGP ASCII-armored public key",
        magic: b"-----BEGIN PGP PUBLIC KEY BLOCK-----",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "asc",
        name_extractor: None,
    },
    Signature {
        name: "PGP-PrivateKey",
        description: "OpenPGP ASCII-armored private key",
        magic: b"-----BEGIN PGP PRIVATE KEY BLOCK-----",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "asc",
        name_extractor: None,
    },
    Signature {
        name: "PGP-Signature",
        description: "OpenPGP ASCII-armored signature",
        magic: b"-----BEGIN PGP SIGNATURE-----",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "sig",
        name_extractor: None,
    },
    Signature {
        name: "PEM",
        description: "PEM-encoded X.509 certificate",
        magic: b"-----BEGIN CERTIFICATE-----",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "pem",
        name_extractor: None,
    },
    Signature {
        name: "MBOX",
        description: "Unix mailbox (mbox)",
        magic: b"From ",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "mbox",
        name_extractor: None,
    },
    Signature {
        name: "PST",
        description: "Microsoft Outlook Personal Storage Table",
        magic: b"!BDN",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "pst",
        name_extractor: None,
    },
    Signature {
        name: "DjVu",
        description: "DjVu document",
        magic: b"AT&TFORM",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "djvu",
        name_extractor: None,
    },
    Signature {
        name: "CRX",
        description: "Chrome extension package",
        magic: b"Cr24",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "crx",
        name_extractor: None,
    },
    Signature {
        name: "Torrent",
        description: "BitTorrent metainfo file (за конвенцією 'announce' — перший ключ у bencode-словнику, не гарантовано специфікацією)",
        magic: b"d8:announce",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "torrent",
        name_extractor: None,
    },
    Signature {
        name: "JKS",
        description: "Java KeyStore",
        magic: b"\xfe\xed\xfe\xed",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "jks",
        name_extractor: None,
    },
    Signature {
        name: "MOBI",
        description: "Amazon Kindle / PalmDOC ebook",
        magic: b"BOOKMOBI",
        relative_offset: 60,
        validator: None,
        end_marker: None,
        extension: "mobi",
        name_extractor: None,
    },
    Signature {
        name: "DWG",
        description: "AutoCAD drawing (AC1027 — версія 2013-2017)",
        magic: b"AC1027",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "dwg",
        name_extractor: None,
    },
    Signature {
        name: "JetDB",
        description: "Microsoft Access database (Jet, .mdb)",
        magic: b"Standard Jet DB",
        relative_offset: 4,
        validator: None,
        end_marker: None,
        extension: "mdb",
        name_extractor: None,
    },
    Signature {
        name: "AceDB",
        description: "Microsoft Access database (ACE, .accdb)",
        magic: b"Standard ACE DB",
        relative_offset: 4,
        validator: None,
        end_marker: None,
        extension: "accdb",
        name_extractor: None,
    },
    Signature {
        name: "SPSS",
        description: "SPSS System File",
        magic: b"$FL2",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "sav",
        name_extractor: None,
    },
    Signature {
        name: "FDF",
        description: "Adobe Forms Data Format",
        magic: b"%FDF-",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "fdf",
        name_extractor: None,
    },
    Signature {
        name: "StuffIt",
        description: "StuffIt archive (класичний Mac OS)",
        magic: b"SIT!",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "sit",
        name_extractor: None,
    },
    Signature {
        name: "ARJ",
        description: "ARJ archive (DOS)",
        magic: b"\x60\xea",
        relative_offset: 0,
        validator: None,
        end_marker: None,
        extension: "arj",
        name_extractor: None,
    },
];

/// Короткий довідковий опис (1-2 речення) — що це за формат і де/ким він
/// типово використовується. Охоплює всі сигнатури з `signature.rs`; для
/// щойно доданих форматів, які ще не потрапили сюди, повертає узагальнену
/// підказку на основі опису сигнатури, а не мовчки лишає панель порожньою.
pub fn usage_note(format: &str) -> &'static str {
    match format {
        "PNG" => "Растрове зображення без втрат (DEFLATE); стандарт де-факто у вебі, іконках ОС і графічних редакторах (PNG Group, 1996).",
        "JPEG" => "Растрове фото зі втратами (DCT-стиснення); основний формат цифрових фотографій і вебзображень (ISO/ITU, 1992).",
        "GIF87a" | "GIF89a" => "Растрове зображення з палітрою до 256 кольорів; 89a додає анімацію. Класика вебу, досі використовується для коротких анімацій (CompuServe).",
        "BMP" | "RDIB" => "Растрове зображення Windows (незжате або RLE); проміжний формат у Windows GDI та старому софті (Microsoft).",
        "ICO" => "Формат іконок Windows: кілька розмірів/глибин кольору в одному файлі (Microsoft).",
        "CUR" | "ANI" => "Формат курсорів Windows (ANI — анімований); використовується провідником та застосунками (Microsoft).",
        "ICNS" => "Формат іконок macOS з кількома роздільностями; використовується Finder і застосунками (Apple).",
        "WEBP" => "Сучасний вебформат зображень Google (з втратами й без), менший за PNG/JPEG при подібній якості (Google, 2010).",
        "TIFF-LE" | "TIFF-BE" => "Гнучкий контейнер растрових зображень з підтримкою шарів і метаданих; широко застосовується у поліграфії й скануванні (Aldus/Adobe).",
        "PSD" => "Рідний формат Adobe Photoshop зі збереженням шарів, масок і стилів (Adobe).",
        "HEIC" | "HEIC-10bit" | "HEIF-mif1" | "HEIF-msf1" | "HEIF-heis" | "HEIF-hevc" => {
            "Формат зображень на основі кодека HEVC; основний формат фото на iOS/macOS (Apple, стандарт MPEG)."
        }
        "AVIF" | "AVIF-sequence" => "Формат зображень на основі кодека AV1; сучасна альтернатива WebP/JPEG у вебі (Alliance for Open Media).",
        "JP2" => "JPEG 2000 — растровий формат з вейвлет-стисненням; застосовується в кіноархівації (DCP) і медичному зображенні (ISO/ITU).",
        "JXL" => "JPEG XL — новий формат зображень з кращим стисненням за JPEG, покликаний замінити JPEG/PNG/GIF у вебі (ISO/IEC).",
        "XCF" => "Рідний формат редактора GIMP зі збереженням шарів (GNU Project).",
        "PSP" => "Рідний формат редактора Paint Shop Pro (Corel/Jasc).",
        "XPM" => "Растровий формат X Window System — зображення записане як масив мовою C (X.Org).",
        "DDS" => "DirectDraw Surface — формат текстур зі стисненням (DXT/BC) для DirectX та ігор (Microsoft).",
        "EXR" => "OpenEXR — зображення з високим динамічним діапазоном (HDR) для кіновиробництва й VFX (Industrial Light & Magic).",
        "JBIG2" => "Стиснення чорно-білих (бінарних) сканованих зображень; найчастіше зустрічається вбудованим у PDF (ITU-T).",
        "PPM" | "PGM" | "PBM" => "Найпростіший текстово/бінарний растровий формат Netpbm для обміну між утилітами Unix.",
        "FLIF" => "Free Lossless Image Format — експериментальний формат без втрат, ідеї якого частково успадкував JPEG XL.",
        "SVG" => "Векторне зображення на основі XML; стандарт вебу для іконок, логотипів та ілюстрацій, що масштабуються (W3C).",
        "EPS" | "EPS-Binary" => "Encapsulated PostScript — векторний формат для поліграфії й вставки ілюстрацій у документи (Adobe).",
        "WMF" | "WMF-Placeable" | "EMF" => {
            "Метафайл Windows (послідовність команд GDI); використовувався для вставки векторної графіки в документи Office (Microsoft)."
        }
        "MNG" | "JNG" => "Анімаційне розширення формату PNG; практично вийшло з ужитку.",
        "PICT" => "Векторно-растровий формат QuickDraw класичного Mac OS — стандарт обміну зображеннями в System 6-9 (Apple).",
        "XFig" => "Формат векторних діаграм редактора Xfig для X Window System.",
        "QOI" => "\"Quite OK Image\" — простий і швидкий формат стиснення зображень без втрат, альтернатива PNG для інструментів.",
        "HDR" => "Формат Radiance для зображень з високим динамічним діапазоном (HDR), застосовується у 3D-рендерингу.",
        "PVR" => "Формат текстур PowerVR для GPU (Imagination Technologies), поширений у мобільних іграх.",
        "CDR" => "Рідний векторний формат редактора CorelDRAW.",

        "ELF" => "Виконувані файли, бібліотеки та об'єктні файли Linux/Unix (Executable and Linkable Format).",
        "PE" => "Виконувані файли й DLL Windows (Portable Executable, Microsoft).",
        "Mach-O-32-BE" | "Mach-O-32-LE" | "Mach-O-64-BE" | "Mach-O-64-LE" | "Mach-O-Fat" => {
            "Виконувані файли macOS/iOS, зокрема універсальні \"fat\"-бінарники з кількома архітектурами (Apple)."
        }
        "PEF" => "Preferred Executable Format — виконувані файли класичного Mac OS для PowerPC (Apple).",
        "Amiga-Hunk" => "Формат виконуваних файлів AmigaOS (Commodore/Amiga).",
        "XCOFF32" | "XCOFF64" => "Формат виконуваних файлів AIX (IBM).",
        "Atari-ST" => "Формат виконуваних файлів (GEMDOS) Atari ST.",
        "Java-Class" => "Скомпільований байткод класу Java (Oracle/Sun).",
        "DEX" => "Байткод Dalvik/ART для застосунків Android (Google).",
        "LNK" => "Ярлик Windows: посилання на файл/програму зі збереженими метаданими цілі (Microsoft).",

        "ZIP" => "Універсальний архів (DEFLATE); основа форматів DOCX/XLSX/JAR/APK та багатьох ігрових контейнерів (PKWARE).",
        "GZIP" => "Стиснення одного потоку даних (DEFLATE); типово для .tar.gz і Content-Encoding у вебі (GNU).",
        "BZIP2" => "Стиснення на основі перетворення Барроуза-Вілера — вищий ступінь стиснення за gzip коштом більшого навантаження на CPU.",
        "TAR" => "Архів Unix, що просто конкатенує файли з заголовками (без стиснення), зазвичай разом з gzip/bzip2/xz.",
        "7Z" => "Архів 7-Zip з високим ступенем стиснення на алгоритмі LZMA, популярний у Windows (Igor Pavlov).",
        "RAR" => "Пропрієтарний архів WinRAR з підтримкою відновлення пошкоджень і розбиття на томи (RARLAB).",
        "CPIO-newc" | "CPIO-crc" | "CPIO-odc" => "Архівний формат Unix cpio; варіант newc використовується у initramfs Linux-ядра.",
        "AR" => "Архів статичних бібліотек Unix (.a) та пакетів .deb (GNU Binutils).",
        "XAR" => "Extensible Archive — контейнер macOS-інсталяторів .pkg (Apple).",
        "ISO9660" => "Образ файлової системи оптичних дисків CD/DVD (ISO).",
        "ZSTD" => "Сучасний швидкий алгоритм стиснення (Facebook/Meta), застосовується у системах збірки й бекапах.",
        "LZ4" => "Надшвидкий алгоритм стиснення з невисоким ступенем компресії — там, де критична швидкість (ігри, БД).",
        "XZ" => "Контейнер стиснення LZMA2 з високим ступенем компресії, типово .tar.xz у Linux-дистрибутивах.",
        "LZO" => "Дуже швидкий алгоритм стиснення, застосовується в завантажувачах ядра Linux та вбудованих системах.",
        "MPQ" => "Архів ресурсів ігор Blizzard (Warcraft III, Diablo II, World of Warcraft).",
        "SquashFS" => "Стиснена файлова система лише для читання, типово для initramfs і Live-дистрибутивів Linux.",
        "CAB" => "Архів Microsoft Cabinet, використовується інсталяторами Windows.",
        "StuffIt" => "Архів StuffIt — історично основний формат стиснення на класичному Mac OS.",
        "ARJ" => "Архівний формат ARJ, популярний у DOS та на BBS у 1990-х.",

        "TTF" | "OTF" | "TTC" => "Шрифт TrueType/OpenType (TTC — колекція шрифтів); стандарт шрифтів в ОС і вебі (Apple/Microsoft, Adobe для OTF).",
        "WOFF" | "WOFF2" => "Веб-формат шрифтів (стиснена обгортка над TTF/OTF) для CSS @font-face (W3C).",
        "BDF" => "Растровий (bitmap) формат шрифтів X Window System (Adobe/X.Org).",

        "glTF-Binary" => "Компактний бінарний 3D-формат для вебу й реального часу — \"JPEG для 3D\" (Khronos Group).",
        "FBX" => "Формат обміну 3D-сценами й анімацією між пакетами (Autodesk).",
        "PLY" => "Полігональний формат для збереження 3D-сіток, отриманих зі сканерів (Stanford).",
        "KTX" | "KTX2" => "Контейнер текстур GPU для OpenGL/Vulkan (Khronos Group).",
        "DWG" => "Рідний формат креслень AutoCAD (Autodesk).",

        "MP3" => "Стиснений з втратами звук (MPEG-1 Layer III) — найпоширеніший аудіоформат (Fraunhofer/ISO).",
        "M4A" | "M4B" | "M4P" => "Контейнер MPEG-4 для аудіо (AAC або ALAC), типово в Apple Music/iTunes.",
        "OGG" => "Відкритий медіаконтейнер Xiph.Org, найчастіше для кодека Vorbis.",
        "ASF" => "Advanced Systems Format Microsoft — контейнер WMV/WMA, попередник сучасних медіаконтейнерів.",
        "WAV" => "Незжатий (PCM) або кодований звук у контейнері RIFF (Microsoft/IBM).",
        "AIFF" | "AIFC" => "Аудіоформат Apple (незжатий або стиснений) — аналог WAV у класичному Mac OS.",
        "8SVX" => "Формат 8-бітного звуку Amiga (IFF 8SVX).",
        "FLAC" => "Стиснення звуку без втрат, популярне для архівування музики.",
        "APE" => "Monkey's Audio — стиснення звуку без втрат з високим ступенем компресії.",
        "WavPack" => "Формат стиснення звуку без втрат (і гібридний режим) з відкритим кодом.",
        "TTA" => "True Audio — формат стиснення звуку без втрат.",
        "DSF" => "Потоковий формат DSD (Direct Stream Digital) для аудіофільських записів (Sony/Philips, стандарт SACD).",
        "CAF" => "Core Audio Format Apple — контейнер для різних аудіокодеків у macOS/iOS.",
        "MIDI" | "RMID" => "Не звук, а послідовність музичних команд (ноти, інструменти) для синтезаторів; RMID — той самий MIDI у контейнері RIFF.",
        "MOD-MK" | "MOD-FLT4" | "MOD-6CHN" | "MOD-8CHN" | "XM" | "S3M" | "IT" => {
            "Трекерний музичний модуль (зразки й партитура в одному файлі) — популярний на Amiga і в дем-сцені."
        }
        "AU" => "Простий аудіоформат Sun/NeXT.",
        "VOC" => "Формат звукових файлів Creative Labs (Sound Blaster).",

        "MP4-isom" | "MP4-mp42" | "MP4-mp41" | "MP4-avc1" | "MP4-iso2" => {
            "Контейнер MPEG-4 для відео/аудіо; основний формат стрімінгу, камер і смартфонів."
        }
        "MOV" => "Контейнер QuickTime Apple — історична основа формату MP4.",
        "3GP" | "3G2" | "3GP-3gp5" => "Контейнер MPEG-4 для мобільних телефонів (стандарт 3GPP).",
        "AVI" => "Контейнер Audio Video Interleave Windows (Microsoft).",
        "EBML" => "Двійковий формат розмітки, на якому побудовані контейнери Matroska (MKV) і WebM.",
        "FLV" => "Контейнер Flash Video — історично використовувався Adobe Flash Player та YouTube.",
        "MPEG-PS" | "MPEG-ES" => "Program Stream/Elementary Stream MPEG-1/2 — застосовується на DVD-Video.",
        "M4V" => "Контейнер MPEG-4 для відео від Apple (захищене відео iTunes / відеоплеєри Apple).",
        "SWF-uncompressed" | "SWF-zlib" | "SWF-lzma" => {
            "Формат Adobe/Macromedia Flash; домінував у вебанімації та браузерних іграх 2000-х до занепаду Flash."
        }
        "Shockwave-Director" => "Файл Adobe/Macromedia Director (проєктор Shockwave) — інтерактивна мультимедіа 1990-2000-х.",
        "RealMedia" => "Контейнер RealAudio/RealVideo (RealNetworks), популярний для стрімінгу в 1990-2000-х.",

        "VMDK" => "Формат віртуального диска VMware.",
        "VHDX" => "Формат віртуального диска Hyper-V (Microsoft).",
        "QCOW2" => "Формат віртуального диска QEMU/KVM з підтримкою знімків (copy-on-write).",
        "VDI" => "Формат віртуального диска VirtualBox (Oracle).",

        "PDF" => "Формат документів з фіксованим макетом для друку й обміну (Adobe, стандарт ISO 32000).",
        "RPM" => "Пакет менеджера пакунків RPM (Red Hat, Fedora, openSUSE).",
        "REG4" | "REG5" => "Файл експорту реєстру Windows (текстовий, різні версії формату) (Microsoft).",
        "BPLIST" => "Бінарний property list — формат конфігурації/серіалізації даних macOS/iOS (Apple).",
        "HDF5" => "Ієрархічний формат наукових даних, застосовується у фізиці й машинному навчанні (моделі Keras) (HDF Group).",
        "NetCDF" => "Формат багатовимірних наукових даних, поширений у метеорології та океанографії (Unidata).",
        "MAT" => "Формат файлів даних MATLAB (MathWorks).",
        "NPY" => "Формат серіалізації масивів бібліотеки NumPy (Python).",
        "Parquet" => "Колонковий формат зберігання даних для великих аналітичних навантажень (Apache).",
        "Avro" => "Формат серіалізації даних зі схемою, типовий для Kafka та Hadoop (Apache).",
        "ORC" => "Колонковий формат зберігання даних, оптимізований для Hive/Hadoop (Apache).",
        "WebVTT" => "Формат субтитрів для тегу <video> у HTML5 (W3C).",
        "ASS" => "Формат субтитрів Advanced SubStation Alpha зі стилізацією тексту, популярний у фан-субтитрах аніме.",
        "PGP-Message" | "PGP-PublicKey" | "PGP-PrivateKey" | "PGP-Signature" => {
            "Дані OpenPGP: зашифроване повідомлення, ключ або підпис (RFC 4880) — застосовується для шифрування й підпису пошти/файлів."
        }
        "PEM" => "Текстове (Base64) кодування криптографічних об'єктів — сертифікатів і ключів (RFC 7468).",
        "MBOX" => "Формат зберігання поштової скриньки як одного файлу з конкатенованих листів (Unix mail).",
        "PST" => "Файл поштової скриньки/архіву Microsoft Outlook.",
        "DjVu" => "Формат сканованих документів з високим стисненням — альтернатива PDF для книг і журналів (LizardTech).",
        "CRX" => "Пакет розширення браузера Google Chrome.",
        "Torrent" => "Файл-метадані BitTorrent (перелік файлів і хеші шматків) для P2P-завантаження.",
        "JKS" => "Java KeyStore — контейнер криптографічних ключів і сертифікатів Java.",
        "MOBI" => "Формат електронних книг Amazon Kindle (Mobipocket).",
        "JetDB" => "Формат бази даних Microsoft Access/Jet (.mdb).",
        "AceDB" => "Формат бази даних наукового ПЗ ACeDB, застосовується в генетиці й біоінформатиці.",
        "SPSS" => "Формат файлів даних статистичного пакету IBM SPSS.",
        "FDF" => "Forms Data Format — дані форм PDF (Adobe).",
        "ICC" => "Профіль колірної корекції: описує колірний простір пристрою (монітор, принтер, камера) для точного відтворення кольору (ICC/ISO 15076).",
        "DPX-BE" | "DPX-LE" => "Digital Picture Exchange — формат кадрів для кіновиробництва: монтаж і архівація фільмів (стандарт SMPTE).",

        "SQLite" => "Файл вбудованої реляційної бази даних SQLite — використовується в мобільних і десктопних застосунках.",
        "Blender" => "Рідний формат файлів проєктів 3D-редактора Blender.",
        "AppleSingle" | "AppleDouble" => {
            "Кодування ресурсної гілки й метаданих класичного Mac OS в один/два файли на не-HFS файлових системах (Apple)."
        }
        "OLE2" => "Composite Document File — контейнер старих форматів Microsoft Office (.doc/.xls/.ppt до 2007).",
        "CHM" => "Compiled HTML Help — довідкові файли Windows (Microsoft).",
        "ILBM" | "ANIM" | "ANBM" => "Растровий/анімаційний формат Amiga на основі IFF (InterLeaved BitMap).",
        "RIFF-PAL" => "Палітра кольорів у контейнері RIFF (Microsoft).",

        "WAD-I" | "WAD-P" => "Формат ресурсів ігор на движку Doom / id Tech (id Software).",
        "PAK-Quake" => "Архів ресурсів гри Quake (id Software).",
        "VBSP" => "Скомпільована карта рівня движка Source (Half-Life 2, Counter-Strike, Portal, TF2 — Valve).",
        "VPK" => "Архів ресурсів движка Source (Valve).",
        "NES" => "Формат ROM-образу iNES для приставки Nintendo NES/Famicom.",
        "Genesis" => "Заголовок ROM-картриджа Sega Genesis/Mega Drive.",
        "UnityFS" => "Формат бандлів ассетів рушія Unity (Unity Technologies).",
        "Godot-PCK" => "Архів ресурсів рушія Godot Engine.",
        "RPA" => "Архів ресурсів рушія візуальних новел Ren'Py.",

        other => match SIGNATURES.iter().find(|sig| sig.name == other) {
            Some(sig) => sig.description,
            None => "Формат без додаткового опису.",
        },
    }
}

/// Повна назва + короткий опис використання (`usage_note`) кожного
/// підтримуваного формату, відсортовані за назвою — спільне джерело для
/// `--formats`/`-f` (CLI, `output::render_formats`) і довідкового
/// спливаючого вікна `?` у TUI, щоб обидва місця завжди показували
/// однакову інформацію.
pub fn all_formats() -> Vec<(&'static str, &'static str)> {
    let mut formats: Vec<(&'static str, &'static str)> =
        SIGNATURES.iter().map(|sig| (sig.name, usage_note(sig.name))).collect();
    // Регістронезалежне сортування — інакше "glTF-Binary" (мала літера)
    // опинився б в самому кінці списку, після "ZSTD".
    formats.sort_unstable_by_key(|(name, _)| name.to_lowercase());
    formats
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_formats_covers_every_signature_exactly_once() {
        let formats = all_formats();
        assert_eq!(formats.len(), SIGNATURES.len());

        let mut names: Vec<&str> = formats.iter().map(|(name, _)| *name).collect();
        names.sort_unstable();
        names.dedup();
        assert_eq!(names.len(), SIGNATURES.len(), "у SIGNATURES є дублікати назв");
    }

    #[test]
    fn all_formats_is_sorted_case_insensitively() {
        let formats = all_formats();
        for pair in formats.windows(2) {
            let (a, _) = pair[0];
            let (b, _) = pair[1];
            assert!(a.to_lowercase() <= b.to_lowercase(), "{a} має йти після {b}");
        }
    }

    #[test]
    fn all_formats_have_non_empty_descriptions() {
        for (name, note) in all_formats() {
            assert!(!note.is_empty(), "{name} має порожній опис");
        }
    }
}
